[tool.poetry]
name = "jarvis-azure"
version = "0.1.1"
description = "Jarvis AI bot, powered by Azure OpenAI"
authors = ["Yusuf Kaka <yusufk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = {extras = ["webhooks","helpers"], version = "^21.3"}
python-dotenv = "^0.21.1"
telegramify-markdown = "^0.3.2"
agno = "^1.1.1"
sqlalchemy = "^2.0.38"
anthropic = "^0.45.2"
azure-ai-inference = "^1.0.0b9"
openai = "^1.65.4"
duckduckgo-search = "^7.5.1"
duckdb = "^1.2.1"
yfinance = "^0.2.54"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
