name: Trigger auto deployment for jarvis-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jarvis-app-AutoDeployTrigger-74c51030-96c2-44b3-8ab6-412628c78c8c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JARVISAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: yusufk.azurecr.io
          registryUsername: ${{ secrets.JARVISAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JARVISAPP_REGISTRY_PASSWORD }}
          containerAppName: jarvis-app
          resourceGroup: jarvis-rg
          imageToBuild: yusufk.azurecr.io/jarvis-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

