name: Trigger auto deployment for jarvis-azure

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jarvis-azure-AutoDeployTrigger-f830c639-45a3-46d3-bcb0-9d347428f715.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JARVISAZURE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JARVISAZURE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JARVISAZURE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.JARVISAZURE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JARVISAZURE_REGISTRY_PASSWORD }}
          containerAppName: jarvis-azure
          resourceGroup: jarvis-rg
          imageToBuild: ghcr.io/jarvis-azure:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

